-- Populate the Users table
insert into users (username, passwordHashed, firstName, lastName, role, lastLogin)
values
    ('admin', SHA2('password1', 256), 'Alice', 'Johnson', 'admin', NOW()),
    ('user1', SHA2('password1', 256), 'Alice', 'Johnson', 'recruiter', NOW()),
    ('user2', SHA2('password2', 256), 'Bob', 'Smith', 'recruiter', NOW()),
    ('user3', SHA2('password3', 256), 'Carol', 'Williams', 'recruiter', NOW()),
    ('user4', SHA2('password4', 256), 'David', 'Brown', 'recruiter', NOW()),
    ('user5', SHA2('password5', 256), 'Eve', 'Davis', 'recruiter', NOW()),
    ('user6', SHA2('password6', 256), 'Frank', 'Miller', 'recruiter', NOW()),
    ('user7', SHA2('password7', 256), 'Grace', 'Wilson', 'recruiter', NOW()),
    ('user8', SHA2('password8', 256), 'Henry', 'Moore', 'recruiter', NOW()),
    ('user9', SHA2('password9', 256), 'Ivy', 'Taylor', 'recruiter', NOW()),
    ('user10', SHA2('password10', 256), 'Jack', 'Anderson', 'recruiter', NOW());


-- Populate the Applicants table with NHS-related data
insert into applicants (firstName, lastName, location, email, phoneNumber, eventAttended, skill)
values
    ('Sarah', 'Connor', 'Cardiff', 'kirill.akbulatov@pm.me', '1234567890', 'NHS Careers Fair', 'Healthcare, Nursing'),
    ('John', 'Doe', 'Swansea', 'kirill.spam1@gmail.com', '2345678901', 'NHS Recruitment Day', 'Healthcare, Public Health'),
    ('Jane', 'Smith', 'Newport', 'ayushyj04@gmail.com', '3456789012', 'Health Conference', 'Nursing, Midwifery'),
    ('Mike', 'Ross', 'Wrexham', 'mross|@example.com', '4567890123', 'NHS Recruitment', 'Clinical Research, Pharmacy'),
    ('Emily', 'Blunt', 'Bangor', 'eblunt@example.com', '5678901234', 'Health Conference', 'Physiotherapy, Occupational Therapy'),
    ('Chris', 'Evans', 'Llandudno', 'cevans@example.com', '6789012345', 'NHS Careers Fair', 'Healthcare, Radiology'),
    ('Anna', 'Taylor', 'Aberystwyth', 'ataylor@example.com', '7890123456', 'Medical Career Day', 'Healthcare, Emergency Medicine'),
    ('Tom', 'Hanks', 'Carmarthen', 'thanks@example.com', '8901234567', 'NHS Recruitment', 'Healthcare, General Practice'),
    ('Sophia', 'Brown', 'Holyhead', 'sbrown@example.com', '9012345678', 'Medical Conference', 'Nursing, Geriatrics'),
    ('Max', 'Steel', 'Merthyr Tydfil', 'msteel@example.com', '1234567899', 'Health Careers Fair', 'Mental Health, Social Work'),
    ('Eva', 'Longoria', 'Bridgend', 'elongoria@example.com', '2345678902', 'Health Careers Event', 'Healthcare, Surgery'),
    ('Jake', 'Gyllenhaal', 'Pontypridd', 'jgyllenhaal@example.com', '3456789013', 'Medical Recruitment Day', 'Nursing, Emergency Care'),
    ('Liam', 'Hemsworth', 'Barry', 'lhemsworth@example.com', '4567890124', 'Health Careers Expo', 'Clinical Psychologist, Healthcare'),
    ('Emma', 'Stone', 'Barry', 'estone@example.com', '5678901235', 'NHS Recruitment Fair', 'Pediatrics, Nursing'),
    ('Olivia', 'Wilde', 'Caerphilly', 'owilde@example.com', '6789012346', 'Health Conference', 'Medical Research, Healthcare'),
    ('Noah', 'Centineo', 'Rhyl', 'ncentineo@example.com', '7890123457', 'NHS Career Expo', 'Pharmacy, Medical Laboratory Technician'),
    ('Lily', 'Collins', 'Abergavenny', 'lcollins@example.com', '8901234568', 'Healthcare Job Fair', 'Nursing, General Medicine'),
    ('Ethan', 'Hawke', 'Llanelli', 'ehawke@example.com', '9012345679', 'Health Expo', 'Healthcare, Radiography'),
    ('Ava', 'DuVernay', 'Conwy', 'aduvernay@example.com', '1234567898', 'NHS Careers Fair', 'Healthcare, Biomedical Science'),
    ('Jack', 'Black', 'Chepstow', 'jblack@example.com', '2345678903', 'Healthcare Recruitment Day', 'Surgery, Health Administration'),
    ('Isabella', 'Clark', 'Cardiff', 'isabella.clark@example.com', '3112234567', 'NHS Careers Expo', 'General Practice, Public Health'),
    ('Mason', 'Lewis', 'Swansea', 'mason.lewis@example.com', '4223345678', 'Health Careers Fair', 'Pharmacy, Radiology'),
    ('Mia', 'Anderson', 'Newport', 'mia.anderson@example.com', '5334456789', 'NHS Recruitment Day', 'Nursing, Pediatrics'),
    ('James', 'Walker', 'Wrexham', 'james.walker@example.com', '6445567890', 'Medical Careers Event', 'Biomedical Science, Surgery'),
    ('Sophia', 'Hall', 'Bangor', 'sophia.hall@example.com', '7556678901', 'Healthcare Job Fair', 'Mental Health, Physiotherapy'),
    ('William', 'Young', 'Llandudno', 'william.young@example.com', '8667789012', 'NHS Careers Day', 'Clinical Research, Occupational Therapy'),
    ('Ella', 'King', 'Aberystwyth', 'ella.king@example.com', '9778890123', 'Health Recruitment Event', 'Emergency Medicine, Nursing'),
    ('Lucas', 'Scott', 'Carmarthen', 'lucas.scott@example.com', '0889901234', 'NHS Careers Expo', 'Public Health, General Practice'),
    ('Charlotte', 'Green', 'Holyhead', 'charlotte.green@example.com', '1991012345', 'Medical Recruitment Fair', 'Surgery, Clinical Psychology'),
    ('Henry', 'White', 'Merthyr Tydfil', 'henry.white@example.com', '2112123456', 'Health Expo', 'Healthcare, Radiology'),
    ('Amelia', 'Moore', 'Bridgend', 'amelia.moore@example.com', '3223234567', 'Healthcare Careers Event', 'Pediatrics, Midwifery'),
    ('Oliver', 'Taylor', 'Pontypridd', 'oliver.taylor@example.com', '4334345678', 'NHS Careers Fair', 'Nursing, Social Work'),
    ('Evelyn', 'Harris', 'Barry', 'evelyn.harris@example.com', '5445456789', 'Medical Recruitment Day', 'Occupational Therapy, Physiotherapy'),
    ('Benjamin', 'Martin', 'Caerphilly', 'benjamin.martin@example.com', '6556567890', 'Health Careers Expo', 'Radiography, Mental Health'),
    ('Aria', 'Thompson', 'Rhyl', 'aria.thompson@example.com', '7667678901', 'NHS Recruitment Day', 'Pharmacy, Biomedical Science'),
    ('Alexander', 'Roberts', 'Abergavenny', 'alexander.roberts@example.com', '8778789012', 'Healthcare Careers Fair', 'Healthcare, Surgery'),
    ('Harper', 'Phillips', 'Llanelli', 'harper.phillips@example.com', '9889890123', 'Medical Careers Expo', 'Nursing, General Medicine'),
    ('Elijah', 'Campbell', 'Conwy', 'elijah.campbell@example.com', '0999901234', 'Health Recruitment Day', 'Clinical Research, Public Health'),
    ('Abigail', 'Parker', 'Chepstow', 'abigail.parker@example.com', '1011012345', 'NHS Careers Day', 'Emergency Medicine, Radiology'),
    ('Jacob', 'Evans', 'Cardiff', 'jacob.evans@example.com', '2122123456', 'Health Careers Fair', 'Healthcare, Midwifery'),
    ('Emily', 'Smith', 'Swansea', 'emily.smith@example.com', '3233234567', 'Medical Recruitment Fair', 'Nursing, Pediatrics'),
    ('Michael', 'Jones', 'Newport', 'michael.jones@example.com', '4344345678', 'NHS Careers Expo', 'General Practice, Biomedical Science'),
    ('Grace', 'Brown', 'Wrexham', 'grace.brown@example.com', '5455456789', 'Healthcare Careers Event', 'Radiography, Mental Health'),
    ('Daniel', 'Davis', 'Bangor', 'daniel.davis@example.com', '6566567890', 'Medical Careers Day', 'Surgery, Clinical Psychology'),
    ('Avery', 'Miller', 'Llandudno', 'avery.miller@example.com', '7677678901', 'NHS Careers Fair', 'Occupational Therapy, Nursing'),
    ('Matthew', 'Wilson', 'Aberystwyth', 'matthew.wilson@example.com', '8788789012', 'Health Careers Expo', 'Pharmacy, Emergency Medicine'),
    ('Ella', 'Clark', 'Carmarthen', 'ella.clark@example.com', '9899890123', 'Medical Recruitment Day', 'Midwifery, Pediatrics'),
    ('Ethan', 'Garcia', 'Holyhead', 'ethan.garcia@example.com', '0900901234', 'NHS Recruitment Day', 'Healthcare, Radiology'),
    ('Sofia', 'Martinez', 'Merthyr Tydfil', 'sofia.martinez@example.com', '1011012346', 'Health Recruitment Fair', 'Nursing, General Medicine'),
    ('James', 'Hernandez', 'Bridgend', 'james.hernandez@example.com', '2122123457', 'NHS Careers Event', 'Biomedical Science, Surgery'),
    ('Lily', 'Lopez', 'Pontypridd', 'lily.lopez@example.com', '3233234568', 'Healthcare Job Fair', 'Mental Health, Social Work'),
    ('Andrew', 'Lee', 'Barry', 'andrew.lee@example.com', '4344345679', 'Health Careers Day', 'Pharmacy, Emergency Medicine'),
    ('Victoria', 'Clarkson', 'Caerphilly', 'victoria.clarkson@example.com', '5455456780', 'NHS Recruitment Fair', 'General Practice, Pediatrics'),
    ('Samuel', 'Hill', 'Rhyl', 'samuel.hill@example.com', '6566567891', 'Medical Careers Expo', 'Nursing, Clinical Research'),
    ('Zoe', 'Hall', 'Abergavenny', 'zoe.hall@example.com', '7677678902', 'Health Expo', 'Physiotherapy, Occupational Therapy'),
    ('Ryan', 'Turner', 'Llanelli', 'ryan.turner@example.com', '8788789013', 'NHS Careers Fair', 'Radiology, Biomedical Science'),
    ('Natalie', 'Morgan', 'Conwy', 'natalie.morgan@example.com', '9899890124', 'Healthcare Careers Event', 'Emergency Medicine, Surgery'),
    ('Caleb', 'Reed', 'Chepstow', 'caleb.reed@example.com', '0900901235', 'Health Recruitment Day', 'Healthcare, Public Health'),
    ('Hazel', 'Baker', 'Cardiff', 'hazel.baker@example.com', '1011012347', 'Medical Careers Fair', 'Nursing, General Medicine'),
    ('Jason', 'Mitchell', 'Swansea', 'jason.mitchell@example.com', '2122123458', 'NHS Careers Expo', 'Occupational Therapy, Midwifery'),
    ('Hannah', 'Hughes', 'Newport', 'hannah.hughes@example.com', '3233234569', 'Health Careers Fair', 'Mental Health, Pediatrics'),
    ('Nathan', 'Carter', 'Wrexham', 'nathan.carter@example.com', '4344345680', 'Healthcare Job Fair', 'Radiography, Surgery'),
    ('Scarlett', 'Adams', 'Bangor', 'scarlett.adams@example.com', '5455456791', 'NHS Recruitment Day', 'Pharmacy, Nursing'),
    ('Christopher', 'Ward', 'Llandudno', 'christopher.ward@example.com', '6566567892', 'Health Careers Event', 'Biomedical Science, Emergency Medicine'),
    ('Amelia', 'Ramirez', 'Aberystwyth', 'amelia.ramirez@example.com', '7677678903', 'Medical Careers Expo', 'General Practice, Clinical Psychology'),
    ('Logan', 'Foster', 'Carmarthen', 'logan.foster@example.com', '8788789014', 'NHS Careers Day', 'Physiotherapy, Public Health'),
    ('Chloe', 'Diaz', 'Holyhead', 'chloe.diaz@example.com', '9899890125', 'Health Recruitment Event', 'Occupational Therapy, Radiology'),
    ('Dylan', 'Hayes', 'Merthyr Tydfil', 'dylan.hayes@example.com', '0900901236', 'Healthcare Careers Fair', 'Surgery, Nursing'),
    ('Aubrey', 'Brooks', 'Bridgend', 'aubrey.brooks@example.com', '1011012348', 'NHS Recruitment Fair', 'Midwifery, Pediatrics'),
    ('Adam', 'Kelly', 'Pontypridd', 'adam.kelly@example.com', '2122123459', 'Health Careers Expo', 'Clinical Research, Emergency Medicine'),
    ('Lillian', 'Sanders', 'Barry', 'lillian.sanders@example.com', '3233234570', 'Medical Careers Day', 'Radiology, General Medicine'),
    ('Cameron', 'Cooper', 'Caerphilly', 'cameron.cooper@example.com', '4344345681', 'NHS Careers Event', 'Nursing, Pharmacy'),
    ('Victoria', 'Murphy', 'Rhyl', 'victoria.murphy@example.com', '5455456792', 'Healthcare Careers Fair', 'Mental Health, Surgery'),
    ('Isaac', 'Rivera', 'Abergavenny', 'isaac.rivera@example.com', '6566567893', 'Health Recruitment Event', 'Public Health, Physiotherapy'),
    ('Lila', 'Flores', 'Llanelli', 'lila.flores@example.com', '7677678904', 'NHS Careers Day', 'Emergency Medicine, Biomedical Science'),
    ('Gavin', 'Powell', 'Conwy', 'gavin.powell@example.com', '8788789015', 'Medical Careers Expo', 'General Practice, Nursing'),
    ('Sophia', 'Cruz', 'Chepstow', 'sophia.cruz@example.com', '9899890126', 'Health Careers Day', 'Midwifery, Radiology'),
    ('Owen', 'Reed', 'Cardiff', 'owen.reed@example.com', '0900901237', 'NHS Recruitment Day', 'Occupational Therapy, Pediatrics'),
    ('Abigail', 'Barnes', 'Swansea', 'abigail.barnes@example.com', '1011012349', 'Healthcare Job Fair', 'Surgery, Clinical Psychology'),
    ('Jaxon', 'Ross', 'Newport', 'jaxon.ross@example.com', '2122123460', 'Medical Recruitment Fair', 'Pharmacy, Emergency Medicine'),
    ('Aurora', 'Patterson', 'Wrexham', 'aurora.patterson@example.com', '3233234571', 'NHS Careers Event', 'Biomedical Science, Public Health'),
    ('Wyatt', 'Ramirez', 'Bangor', 'wyatt.ramirez@example.com', '4344345682', 'Health Careers Expo', 'Radiology, Nursing'),
    ('Zoe', 'Griffin', 'Llandudno', 'zoe.griffin@example.com', '5455456793', 'Healthcare Careers Event', 'Mental Health, Surgery'),
    ('Eli', 'Gonzalez', 'Aberystwyth', 'eli.gonzalez@example.com', '6566567894', 'NHS Recruitment Fair', 'Pediatrics, Clinical Research'),
    ('Layla', 'Bryant', 'Carmarthen', 'layla.bryant@example.com', '7677678905', 'Health Recruitment Event', 'Midwifery, General Medicine'),
    ('Adrian', 'Alexander', 'Holyhead', 'adrian.alexander@example.com', '8788789016', 'NHS Careers Expo', 'Physiotherapy, Emergency Medicine'),
    ('Victoria', 'Coleman', 'Merthyr Tydfil', 'victoria.coleman@example.com', '9899890127', 'Healthcare Careers Fair', 'Nursing, Radiology');

-- Populate the Applicant Preferences table with sample data
insert into applicantPreferences (applicationId, SubscribeToNewsLetter, SubscribeToBulletins, SubscribeToJobUpdates)
values
    (1, 'yes', 'no', 'yes'),
    (2, 'yes', 'yes', 'no'),
    (3, 'yes', 'yes', 'yes'),
    (4, 'no', 'yes', 'yes'),
    (5, 'no', 'yes', 'no'),
    (6, 'no', 'no', 'no'),
    (7, 'no', 'no', 'no'),
    (8, 'no', 'no', 'yes'),
    (9, 'no', 'yes', 'yes'),
    (10, 'no', 'no', 'no'),
    (11, 'no', 'yes', 'yes'),
    (12, 'no', 'yes', 'no'),
    (13, 'no', 'no', 'yes'),
    (14, 'no', 'yes', 'yes'),
    (15, 'no', 'yes', 'no'),
    (16, 'no', 'yes', 'yes'),
    (17, 'no', 'no', 'yes'),
    (18, 'no', 'no', 'yes'),
    (19, 'no', 'yes', 'yes'),
    (20, 'no', 'yes', 'no');

-- Populate the Application Details table
insert into applicationdetails(applicationId, currentPosition, status, CvPath, CoverLetterPath)
values
    (1, 'Nurse', 'External', NULL, NULL),
    (2, 'Public Health Analyst', 'External', NULL, NULL),
    (3, 'Midwife', 'Internal', NULL, NULL),
    (4, 'Clinical Researcher', 'External', NULL, NULL),
    (5, 'Physiotherapist', 'Internal', NULL, NULL),
    (6, 'Radiology Technician', 'External', NULL, NULL),
    (7, 'Emergency Medicine Doctor', 'External', NULL, NULL),
    (8, 'General Practitioner', 'External', NULL, NULL),
    (9, 'Geriatric Nurse', 'Internal', NULL, NULL),
    (10, 'Mental Health Counselor', 'External', NULL, NULL),
    (11, 'Pharmacist', 'Internal', NULL, NULL),
    (12, 'Medical Lab Technician', 'External', NULL, NULL),
    (13, 'Pediatric Nurse', 'Internal', NULL, NULL),
    (14, 'Medical Researcher', 'External', NULL, NULL),
    (15, 'Surgical Nurse', 'External', NULL, NULL),
    (16, 'Radiographer', 'Internal', NULL, NULL),
    (17, 'Biomedical Scientist', 'External', NULL, NULL),
    (18, 'Surgical Assistant', 'External', NULL, NULL),
    (19, 'Healthcare Administrator', 'Internal', NULL, NULL),
    (20, 'Health Coordinator', 'External', NULL, NULL);


DESCRIBE users;
